name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Lint
        if: always()
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout 3m --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: go test ./... -v

      - name: Report coverage
        run: go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov
