name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      # this setups up coredns and kube-proxy too
      - uses: actions/checkout@master

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:v1.20.15

      - name: Get kind cluster information
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Setup cluster-autoscaler
        run: ./e2e/cluster-autoscaler-install.sh

      - name: Setup aws-node
        run: kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.11.0/config/master/aws-k8s-cni.yaml

