name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      # this setups up coredns too
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: v1.21.1

      - name: Get kind cluster information
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

#      - name: Set up Helm
#        uses: azure/setup-helm@v1
#        with:
#          version: v3.8.1

      - name: Setup cluster-autoscaler
        run: ./e2e/cluster-autoscaler-install.sh
